// Package ui provides a professional menu engine for the Telegram bot.
//
// Design goals:
//   - Every screen is an EditMessageText/EditMessageReplyMarkup call — never
//     a new SendMessage — to avoid chat spam.
//   - Per-user debounce (500 ms) prevents double-click ghost actions.
//   - Callback data is always ≤ 64 bytes (Telegram hard limit).
//   - Rendered keyboards are cached with a 5-second TTL so rapid back/forward
//     navigation doesn't re-query the DB every tap.
//   - A navigation stack supports unlimited nested menus with a single "⬅️ Voltar"
//     button at every level.
//   - MenuState is the single unit of composition: register once, route everywhere.
package ui

import (
	"fmt"
	"sync"
	"time"
)

// ─── Menu primitives ──────────────────────────────────────────────────────────

// Button is a single inline keyboard cell.
type Button struct {
	Label    string
	Callback string // must be ≤ 64 bytes
}

// Row is a horizontal group of buttons.
type Row []Button

// Menu is the full content of one rendered screen.
type Menu struct {
	Caption string // Markdown caption / photo caption
	Rows    []Row
}

// ─── MenuState ────────────────────────────────────────────────────────────────

// MenuState is the definition of one screen in the menu graph.
// Register all states with the global Engine via Engine.Register().
type MenuState struct {
	// ID is the unique screen identifier used in callback routing.
	// Keep short (≤20 chars) — it will appear in callback data.
	ID string

	// Render builds the visible content for the given user.
	// Must be pure (no side-effects) so it can be cached.
	Render func(userID int64, args string) Menu

	// Handle is called when the user taps any button generated by this screen.
	// callback is the full Telegram callback_data string.
	Handle func(userID int64, callback string)
}

// ─── Navigation stack ─────────────────────────────────────────────────────────

type navStack struct {
	mu    sync.Mutex
	stack map[int64][]string // userID → []stateID (most recent last)
}

func (ns *navStack) push(userID int64, stateID string) {
	ns.mu.Lock()
	defer ns.mu.Unlock()
	ns.stack[userID] = append(ns.stack[userID], stateID)
	if len(ns.stack[userID]) > 20 { // cap depth
		ns.stack[userID] = ns.stack[userID][1:]
	}
}

// pop removes and returns the previous state (or "" if empty).
func (ns *navStack) pop(userID int64) string {
	ns.mu.Lock()
	defer ns.mu.Unlock()
	s := ns.stack[userID]
	if len(s) == 0 {
		return ""
	}
	prev := s[len(s)-1]
	ns.stack[userID] = s[:len(s)-1]
	return prev
}

func (ns *navStack) clear(userID int64) {
	ns.mu.Lock()
	defer ns.mu.Unlock()
	delete(ns.stack, userID)
}

// ─── Debounce ─────────────────────────────────────────────────────────────────

const debounceDuration = 500 * time.Millisecond

type debouncer struct {
	mu   sync.Mutex
	last map[int64]time.Time
}

// Allow returns true when the user is NOT within the debounce window.
func (d *debouncer) Allow(userID int64) bool {
	d.mu.Lock()
	defer d.mu.Unlock()
	if t, ok := d.last[userID]; ok && time.Since(t) < debounceDuration {
		return false
	}
	d.last[userID] = time.Now()
	return true
}

// ─── Render cache ─────────────────────────────────────────────────────────────

const cacheTTL = 5 * time.Second

type cacheEntry struct {
	menu    Menu
	expires time.Time
}

type renderCache struct {
	mu      sync.RWMutex
	entries map[string]cacheEntry // key: stateID+":"+userID
}

func (c *renderCache) key(stateID string, userID int64, args string) string {
	return fmt.Sprintf("%s:%d:%s", stateID, userID, args)
}

func (c *renderCache) get(stateID string, userID int64, args string) (Menu, bool) {
	c.mu.RLock()
	defer c.mu.RUnlock()
	e, ok := c.entries[c.key(stateID, userID, args)]
	if !ok || time.Now().After(e.expires) {
		return Menu{}, false
	}
	return e.menu, true
}

func (c *renderCache) set(stateID string, userID int64, args string, m Menu) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.entries[c.key(stateID, userID, args)] = cacheEntry{menu: m, expires: time.Now().Add(cacheTTL)}
}

func (c *renderCache) invalidate(userID int64) {
	c.mu.Lock()
	defer c.mu.Unlock()
	prefix := fmt.Sprintf(":%d:", userID)
	for k := range c.entries {
		if len(k) > len(prefix) {
			for i := range k {
				if k[i:i+len(prefix)] == prefix {
					delete(c.entries, k)
					break
				}
			}
		}
	}
}

// ─── Callback compression ─────────────────────────────────────────────────────

// CompressCallback ensures that callback_data stays within Telegram's 64-byte
// hard limit. If the raw data is ≤64 bytes it is returned unchanged. Otherwise
// the caller should register a short alias in a side-table; this function only
// validates and panics in dev mode so you notice the issue at startup.
func CompressCallback(data string) string {
	if len(data) > 64 {
		// In production: log and truncate. In dev: panic so it's caught early.
		panic(fmt.Sprintf("ui: callback data exceeds 64 bytes (%d): %q", len(data), data))
	}
	return data
}

// SafeCallback is like CompressCallback but truncates silently instead of
// panicking — use in production paths where a silent failure is better than a
// crash.
func SafeCallback(data string) string {
	if len(data) > 64 {
		return data[:64]
	}
	return data
}

// ─── Pagination helpers ───────────────────────────────────────────────────────

// PageSize is the default number of items per paginated menu.
const PageSize = 8

// PaginateItems slices any slice for the requested page (0-indexed).
// Returns the slice window, total pages count, and whether it's the last page.
func PaginateItems[T any](items []T, page int) (window []T, totalPages int, isLast bool) {
	if len(items) == 0 {
		return nil, 0, true
	}
	totalPages = (len(items) + PageSize - 1) / PageSize
	if page < 0 {
		page = 0
	}
	if page >= totalPages {
		page = totalPages - 1
	}
	start := page * PageSize
	end := start + PageSize
	if end > len(items) {
		end = len(items)
	}
	return items[start:end], totalPages, page == totalPages-1
}

// NavRow builds a standard pagination navigation row.
//   - prefix is the callback prefix (e.g. "inv_page")
//   - page is the current 0-indexed page
//   - totalPages is the total number of pages
func NavRow(prefix string, page, totalPages int) Row {
	var row Row
	if page > 0 {
		row = append(row, Button{"◀️", fmt.Sprintf("%s_%d", prefix, page-1)})
	}
	row = append(row, Button{fmt.Sprintf("%d/%d", page+1, totalPages), "_noop"})
	if page < totalPages-1 {
		row = append(row, Button{"▶️", fmt.Sprintf("%s_%d", prefix, page+1)})
	}
	return row
}

// ─── Engine ───────────────────────────────────────────────────────────────────

// Engine is the central menu coordinator. Create one instance (Global below)
// and register all MenuState definitions before the bot starts processing
// updates.
type Engine struct {
	states   map[string]*MenuState
	statesMu sync.RWMutex

	nav      navStack
	bounce   debouncer
	cache    renderCache
}

// NewEngine returns a ready-to-use Engine.
func NewEngine() *Engine {
	return &Engine{
		states: map[string]*MenuState{},
		nav:    navStack{stack: map[int64][]string{}},
		bounce: debouncer{last: map[int64]time.Time{}},
		cache:  renderCache{entries: map[string]cacheEntry{}},
	}
}

// Global is the singleton Engine used by all handlers.
var Global = NewEngine()

// Register adds a MenuState to the engine. Panics on duplicate IDs.
func (e *Engine) Register(s *MenuState) {
	e.statesMu.Lock()
	defer e.statesMu.Unlock()
	if _, exists := e.states[s.ID]; exists {
		panic(fmt.Sprintf("ui: MenuState %q already registered", s.ID))
	}
	e.states[s.ID] = s
}

// Render returns the Menu for stateID, using the cache when warm.
func (e *Engine) Render(stateID string, userID int64, args string) (Menu, bool) {
	e.statesMu.RLock()
	s, ok := e.states[stateID]
	e.statesMu.RUnlock()
	if !ok {
		return Menu{}, false
	}
	if m, hit := e.cache.get(stateID, userID, args); hit {
		return m, true
	}
	m := s.Render(userID, args)
	e.cache.set(stateID, userID, args, m)
	return m, true
}

// Dispatch routes a Telegram callback to the correct state handler.
// Returns false if the userID is within the debounce window (drop the update).
func (e *Engine) Dispatch(userID int64, callback string) bool {
	if !e.bounce.Allow(userID) {
		return false
	}
	e.statesMu.RLock()
	defer e.statesMu.RUnlock()
	for _, s := range e.states {
		if s.Handle != nil {
			s.Handle(userID, callback)
			return true
		}
	}
	return false
}

// NavigateTo pushes the current screen onto the stack and moves to stateID.
func (e *Engine) NavigateTo(userID int64, currentStateID, targetStateID string) {
	e.nav.push(userID, currentStateID)
	e.cache.invalidate(userID)
}

// NavigateBack pops the navigation stack and returns the previous stateID.
// Returns "" if the stack is empty.
func (e *Engine) NavigateBack(userID int64) string {
	return e.nav.pop(userID)
}

// InvalidateCache clears all cached renders for a user (call after mutations).
func (e *Engine) InvalidateCache(userID int64) {
	e.cache.invalidate(userID)
}

// ResetNavigation clears the navigation stack for a user (call on main menu).
func (e *Engine) ResetNavigation(userID int64) {
	e.nav.clear(userID)
}

// BackButton returns a standard "⬅️ Voltar" Button that navigates to the given
// stateID. Use in every menu's last row.
func BackButton(targetCallback string) Button {
	return Button{"⬅️ Voltar", SafeCallback(targetCallback)}
}
